MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "/data1/Code/wuwentao/pre_model/0921_vehiclemaev2_100W_mask75/checkpoint-100.pth"
  NAME: 'transformer'
  DEVICE_ID: ('0,1')  # 修改为您可用的GPU编号，如果使用CPU可以设置为空或('cpu')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True
  SIE_VIEW: True
  SIE_COE: 3.0
  JPM: True
  SHIFT_NUM: 8
  RE_ARRANGE: True
INPUT:
  # SIZE_TEST: [256, 256]
  SIZE_TEST: [384, 128]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
DATASETS:
  NAMES: ('veri')
  ROOT_DIR: ('/data1/Datasets/Seg/cocostuff/images/train/')  # 修改为您的数据集目录
TEST:
  EVAL: True
  IMS_PER_BATCH: 32  # 如果GPU内存不足，可以减小这个值
  RE_RANKING: False
  WEIGHT: "/data1/Code/wuwentao/pre_model/0921_vehiclemaev2_100W_mask75/checkpoint-100.pth" # 修改为您的模型权重文件路径
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
OUTPUT_DIR: './output'  # 修改为您想保存结果的目录